# Example
# https://gitpod.io/#https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/tree/lwolf-gitpod

image: gitpod/workspace-full

tasks:
  - name: RenderT3Docs

    command: |
      eval "$(docker run --rm t3docs/render-documentation:develop show-shell-commands)"
      dockrun_t3rd makehtml-no-cache

ports:
  - port: 8001
    name: apache
    onOpen: ignore